version: "3.7"
services:
  db:
    container_name: mongo_dev
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME= admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'
